//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEntry
    {
        public int Id { get; set; }
        public string info { get; set; }
        public System.DateTime date_entered { get; set; }
        public string username { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual HOA HOA { get; set; }
        public virtual PropertyManager PropertyManager { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
