//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string address1 { get; set; }
        public string city { get; set; }
        public string middle_initial { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string address2 { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
    }
}
