//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public int id { get; set; }
        public System.DateTime time_placed { get; set; }
        public Nullable<System.DateTime> time_completed { get; set; }
        public string summary { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> next_eta { get; set; }
        public string followup_notes { get; set; }
        public bool followup_required { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
