//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileContainer
    {
        public string file_name { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public int file_id { get; set; }
        public long file_size { get; set; }
    
        public virtual File File { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Property Property { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual HOA HOA { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual PropertyManager PropertyManager { get; set; }
    }
}
