//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_PropertyManagerHistory
    {
        public int id { get; set; }
        public System.DateTime date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int hoa_id { get; set; }
        public int property_manager_id { get; set; }
    
        public virtual HOA HOA { get; set; }
        public virtual PropertyManager PropertyManager { get; set; }
    }
}
