//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Contacts = new HashSet<Contact>();
            this.LedgerRecords = new HashSet<LedgerRecord>();
            this.Properties = new HashSet<Property>();
            this.FileContainers = new HashSet<FileContainer>();
            this.AuditEntries = new HashSet<AuditEntry>();
        }
    
        public int id { get; set; }
        public string company_name { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<LedgerRecord> LedgerRecords { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<FileContainer> FileContainers { get; set; }
        public virtual ICollection<AuditEntry> AuditEntries { get; set; }
    }
}
