//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingStall
    {
        public string stall { get; set; }
        public int id { get; set; }
        public int property_id { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
