//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PropMgmtDBContainer : DbContext
    {
        public PropMgmtDBContainer()
            : base("name=PropMgmtDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<ParkingStall> ParkingStalls { get; set; }
        public virtual DbSet<ServiceCall> ServiceCalls { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<GateCode> GateCodes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<HOA> HOAs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<PropertyManager> PropertyManagers { get; set; }
        public virtual DbSet<HOA_PropertyManagerHistory> HOA_PropertyManagerHistories { get; set; }
        public virtual DbSet<UtilitiesPaymentHistory> UtilitiesPaymentHistories { get; set; }
        public virtual DbSet<LedgerRecord> LedgerRecords { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ChargeType> ChargeTypes { get; set; }
        public virtual DbSet<BusinessType> BusinessTypes { get; set; }
        public virtual DbSet<UtilitiesType> UtilitiesTypes { get; set; }
        public virtual DbSet<DepositType> DepositTypes { get; set; }
        public virtual DbSet<Correspondence> Correspondences { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileContainer> FileContainers { get; set; }
        public virtual DbSet<AuditEntry> AuditEntries { get; set; }
    }
}
