//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Tenants = new HashSet<Tenant>();
            this.ServiceCalls = new HashSet<ServiceCall>();
            this.GateCodes = new HashSet<GateCode>();
            this.ParkingStalls = new HashSet<ParkingStall>();
            this.UtilitiesPaymentHistories = new HashSet<UtilitiesPaymentHistory>();
            this.FileContainers = new HashSet<FileContainer>();
            this.AuditEntries = new HashSet<AuditEntry>();
        }
    
        public int id { get; set; }
        public string address1 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string address2 { get; set; }
        public string mailbox_info { get; set; }
        public bool owner_pays_utilities { get; set; }
        public Nullable<int> hoa_id { get; set; }
        public int owner_id { get; set; }
    
        public virtual ICollection<Tenant> Tenants { get; set; }
        public virtual ICollection<ServiceCall> ServiceCalls { get; set; }
        public virtual ICollection<GateCode> GateCodes { get; set; }
        public virtual ICollection<ParkingStall> ParkingStalls { get; set; }
        public virtual ICollection<UtilitiesPaymentHistory> UtilitiesPaymentHistories { get; set; }
        public virtual HOA HOA { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<FileContainer> FileContainers { get; set; }
        public virtual ICollection<AuditEntry> AuditEntries { get; set; }
    }
}
