//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCall
    {
        public int id { get; set; }
        public System.DateTime time_placed { get; set; }
        public Nullable<System.DateTime> time_completed { get; set; }
        public string summary { get; set; }
        public string notes { get; set; }
        public int invoice_nbr { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> amount_due { get; set; }
        public Nullable<System.DateTime> next_eta { get; set; }
        public int property_id { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
