//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMgmt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.contact_id = 0;
            this.Vehicles = new HashSet<Vehicle>();
            this.LedgerRecords = new HashSet<LedgerRecord>();
            this.Correspondences = new HashSet<Correspondence>();
            this.FileContainers = new HashSet<FileContainer>();
            this.AuditEntries = new HashSet<AuditEntry>();
        }
    
        public int id { get; set; }
        public System.DateTime lease_start { get; set; }
        public System.DateTime lease_end { get; set; }
        public int rent_amt { get; set; }
        public bool section8 { get; set; }
        public int property_id { get; set; }
        public int contact_id { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<LedgerRecord> LedgerRecords { get; set; }
        public virtual ICollection<Correspondence> Correspondences { get; set; }
        public virtual ICollection<FileContainer> FileContainers { get; set; }
        public virtual ICollection<AuditEntry> AuditEntries { get; set; }
    }
}
